### ISSUE TITLE
Add short demo of usage in your README

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/ezmodelR#15]
I suggest that you add a short demo of usage in your README. I see that you link to your vignette, but someone just quickly looking might not bother to click and read the whole vignette. I'd just paste my most interesting and useful example from the vignette here. Think of it as advertising to capture users for your package. If you don't have this in your Python package README, I would add that too.

**Comment by conleyst** [comment]
exists as of `d0b881c`
