### ISSUE TITLE
Function documentation is incomplete and not formatted correctly

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/ezmodelR#17]
When I install your package and try to use the help to read your function documentation I get errors:
```
> ?score
No documentation for ‘score’ in specified packages and libraries:
you could try ‘??score’
> ?train_test_plot
No documentation for ‘train_test_plot’ in specified packages and libraries:
you could try ‘??train_test_plot’
> ?score
No documentation for ‘score’ in specified packages and libraries:
you could try ‘??score’
> ?regularization_plot
No documentation for ‘regularization_plot’ in specified packages and libraries:
you could try ‘??regularization_plot’
```
I think this is because you do not use ROxygen formatted documentation with your functions in the `.R` file. See how to fix this in [the object documentation chapter](http://r-pkgs.had.co.nz/man.html) from R packages by Hadley Wickham.

**Comment by conleyst** [comment]
fixed as of `aeea38b`
