### ISSUE TITLE
Almost no documentation in tests

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/ezmodelR#18]
There is exactly 1 comment in `test_regularization_plot.R`. This is not sufficient to make your code readable by others. Please address.

**Comment by ttimbers** [comment]
Specifically, in your comments you should specify which function these tests are for (this is especially important for your case since you decided to group your functions and test functions all in one file instead of separating them into separate files).

**Comment by conleyst** [comment]
@ttimbers Thanks for the feedback on the documentation. I'm a little confused about the your comment about having decided to group functions and test functions together. It seems to me they're in two different files? And I documented which functions depended on which tests in the documentation file in the `tests` directory

**Comment by ttimbers** [comment]
I meant that your `.R` for functions has more than one function, and your `.R` for tests has tests for different functions in it. Oftentimes you only put one function in a `.R` and all the tests for that one function in another `.R` (no other functions are tested in that `.R`). Make sense? What you did is valid however, I think you just need to add more documentation to make it clear what tests belong to which function.

**Comment by conleyst** [comment]
@ttimbers  Oh, I understand. Thanks for clearing that up. Do I need any more documentation about which test is for which function than is contained here -- https://github.com/UBC-MDS/ezmodelR/blob/master/tests/documentation.md ?
