### ISSUE TITLE
Something preventing `devtools::spell_check()` from working

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/ezmodelR#23]
Something is preventing `devtools::spell_check()` from working... I have never seen this before... Maybe if you address some of the other problems this will go away? Please check. If not, we can work together to solve this (and then find out if you have any spelling errors :wink:).

```
> devtools::spell_check()
Error in sprintf(fmt, "  WORD") : 
  invalid format '%--Inf'; use format %s for character objects
In addition: Warning message:
In max(nchar(words)) : no non-missing arguments to max; returning -Inf
```

**Comment by tylercroberts** [comment]
2aacedd587fc5e709432c63300858ac7d9e94e85 should have fixed any remaining issues with devtools checks.
