### ISSUE TITLE
Coverage claim does not match tests

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/ezmodelR#24]
In your [coverage docs](https://github.com/UBC-MDS/ezmodelR/blob/v3/tests/documentation.md) you list at least 8 tests, but when I run `devtools::test()` it says there are only 4. This is what I also see in the `tests` dir... You likely need more than 4 tests for 100% branch coverage...

```
> devtools::test()
Loading ezmodelR
Testing ezmodelR
✔ | OK F W S | Context
⠸ |  4       | 0Error in parse(textConnection(lines, encoding = "UTF-8"), n = -1, srcfile = srcfile,  : 
  /Users/timberst/Downloads/ezmodelR-3/tests/testthat/test_score.R:4:40: unexpected '{'
3: 
4: test_that("score() returns a function" {
                                          ^

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 6.8 s

OK:       4
Failed:   0
Warnings: 0
Skipped:  0
```

**Comment by conleyst** [comment]
@ttimbers Did you have a chance to look at the `documentation.md` files in the test directory?

**Comment by ttimbers** [comment]
Yes, that's what I linked to above - [coverage docs](https://github.com/UBC-MDS/ezmodelR/blob/v3/tests/documentation.md)

**Comment by conleyst** [comment]
@ttimbers Then I'm a little unclear why you feel some functions might not have tests?

It might be an issue with the syntax in the test file. We noticed that some commas were missing. Is that perhaps it?

**Comment by ttimbers** [comment]
Because `devtools::test()` says there are only 4 tests. And when I looked at the milestone 2 code I thought I could only see 4 tests as well. This may be clearer now that you have split them into separate files and added more comments to your test code.
